apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 317105901372.dkr.ecr.ap-south-1.amazonaws.com/frontend-prod:e0e59d6a45dd9922354c44df6434eb269e85f7e7
          ports:
            - containerPort: 80