apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: ecommerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: db-secret   # 👈 K8s secret name
    creationPolicy: Owner

  data:
    - secretKey: DB_HOST
      remoteRef:
        key: prod/db-credentials
        property: host

    - secretKey: DB_USER
      remoteRef:
        key: prod/db-credentials
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/db-credentials
        property: password

    - secretKey: DB_NAME
      remoteRef:
        key: prod/db-credentials
        property: database

    - secretKey: DB_PORT
      remoteRef:
        key: prod/db-credentials
        property: port