name: cloudnative-platform-image-build

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  ECR_Deployment:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Setup Node (for lint + test)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      # 3. Install dependencies (Frontend example)
      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      # 4. Lint Code
      - name: Run Lint
        run: |
          cd frontend
          npm run lint || echo "No lint configured"

      # 5. Run Tests
      - name: Run Tests
        run: |
          cd frontend
          npm test -- --watchAll=false || echo "No tests configured"

      # 6. Configure AWS (OIDC)
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
          aws-region: us-east-1

      # 7. Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 8. Set Image Tag (IMPORTANT 🔥)
      - name: Set Image Tag
        id: vars
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 9. Build Docker Image
      - name: Build Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG docker/frontend/.
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # 10. Push Docker Image
      - name: Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest