name: Prod Pipeline

on:
  push:
    branches: [ main ]

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yaml
    with:
      ecr_repository: frontend-prod

  cd:
    needs: ci
    uses: ./.github/workflows/reusable-cd.yaml
    with:
      image_tag: ${{ needs.ci.outputs.image_tag }}
      ecr_uri: 317105901372.dkr.ecr.us-east-1.amazonaws.com/frontend-prod
      manifest_path: kubernetes/manifests/prod/frontend-deployment.yaml
      environment: prod